### ISSUE TITLE
iBreakDown article goes to arxiv

### ISSUE THREAD

**Issue by pbiecek** [ModelOriented/iBreakDown#23]
Please ask someone for review of the iBreakDown article
upload iBreakDown article to arxiv
add link to it in README.md, CITATION and maybe DESCRIPTION

**Comment by agosiewska** [comment]
upload code for generating plots and link to it
After #26

**Comment by agosiewska** [comment]
iBreakDown is on arxiv
https://arxiv.org/abs/1903.11420

**Comment by pbiecek** [comment]
Thanks
