### ISSUE TITLE
Enhancement of label-functionality

### ISSUE THREAD

**Issue by GerardMeester** [ModelOriented/iBreakDown#37]
It would be nice if the plot function of iBreakdown would have 2 extra arguments:

1) One argument to add a subtitle, which can be used for a case-specific label (for example the identification and name of the case).
Instead of having to override the model-label.

2) An argument to specifiy user-friendly variable labels, which than can be used in the breakdown plot instead of the technical variable-names used in the model. This is especially useful in the communication with end-users about the explanation of the prediction (which is one of the goals of explaining models).

**Comment by pbiecek** [comment]
fixed in b2e96a0
