### ISSUE TITLE
description() needs at least 4 features to work

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/iBreakDown#50]

**Comment by hbaniecki** [comment]
Force short description when less than 3 features (?)

**Comment by pbiecek** [comment]
@AdamIzdebski is it still an issue?

**Comment by AdamIzdebski** [comment]
@pbiecek 
No, it is not. 
https://github.com/ModelOriented/iBreakDown/blob/3451acb8899bdf384676e567b1ee7b7d1f09d2a2/R/describe_breakdown.R#L108-L110
