### ISSUE TITLE
generating SHAP values.

### ISSUE THREAD

**Issue by sandeshregmi** [ModelOriented/iBreakDown#64]
Hello,
First of all thank you so much for your contribution for making millions of like me more educated on "Black Box" model.
I have a quick question regarding SHAP values generation using DALEX/ iBreakDown packages.
`xgb<-DALEX::explain(xgb_03, data=testing[,1:345],y= testing$TRANSITIONED=="YES", label = "for Member "L00274353401")`

`ive_xgb <- iBreakDown::shap(xgb, new_observation = filter(testing[,1:345], MEMBER=='TX00274353401'))`

When I run this code, first object gets created without problem but for second object (ive_xgb), its still running after three hours. Do you have any suggestion? please
Thank you

**Comment by pbiecek** [comment]
For complex models it may be slow. 
One quick trick is to reduce number of random paths calculated by this function. By default it's 25, you can try B = 5, should be fine for medium or small number of variables in the model (but you have >300 so you need to check if it will be stable). 
Second will be to give smaller data to the explain() function. 
If `testing` is very large you can try to use just a subset of data.

**Comment by sandeshregmi** [comment]
I appreciate it. Let me give it a try.
