### ISSUE TITLE
plotting SHAP object

### ISSUE THREAD

**Issue by sandeshregmi** [ModelOriented/iBreakDown#65]
Hello,
In the last line of following code, I am trying to plot top 30 highest contributing predictors. I added max_features =30, but the output did not change. Any suggestion please?
`testing_rand<- testing[sample(nrow(testing),500),]
xgb<-DALEX::explain(xgb_03, data=testing_rand[,1:345],y= testing_rand$TRANSITIONED=="YES", label = "for Member FLU1533123501")
ive_xgb <- iBreakDown::shap(xgb, new_observation = filter(testing_rand[,1:345], MEMBER=='FLU1533123501'), B=5)`
`plot(ive_xgb, max_features =30)`

**Comment by hbaniecki** [comment]
Hi! Indeed, the shap `plot` does not have a `max_features` argument yet. For now, you can explore the `plotD3` function with `max_features` and `bar_width` arguments.

**Comment by sandeshregmi** [comment]
I tried `plot3D()` but got stuck. How do I order top 30 most influential predictors ?
Thank you

**Comment by pbiecek** [comment]
It is now implemented with the `max_features` argument 
with https://github.com/ModelOriented/iBreakDown/commit/2b869c5514124e302217b14ebac5261f1e295ccc
