### ISSUE TITLE
Differentely calculated diffs in local_attributions and local_interactions

### ISSUE THREAD

**Issue by WojciechKretowicz** [ModelOriented/iBreakDown#70]
https://github.com/ModelOriented/iBreakDown/blob/43b6e0bf9789d39b0d740a6faba7641e36fe7868/R/local_attributions.R#L126

https://github.com/ModelOriented/iBreakDown/blob/43b6e0bf9789d39b0d740a6faba7641e36fe7868/R/local_interactions.R#L143

**Comment by pbiecek** [comment]
both lead to same results, but shall be more consistent for readability
let's use ()^2 in the local_interactions as well

**Comment by pbiecek** [comment]
ok, in fact I'm going to use sqrt(mean(x-y)^2) which is equivalent to |x-y| 
it's easier
