### ISSUE TITLE
Hidden last contribution label in the break_down plot

### ISSUE THREAD

**Issue by hbaniecki** [ModelOriented/iBreakDown#85]
@hbaniecki Thank you for pointing us the docs for iBreakDown, etc.! 
I don't know if this is helpful but I got this minor issue a while ago for binary classification models. 
The prediction for the positive cases works fine, but for negative cases the prediction becomes unreadable. 
![image](https://user-images.githubusercontent.com/37885260/80011740-d9de3700-84fe-11ea-82dd-591dbd25dc46.png)

adding vcolors to the generic plot function worked for me:
```
bd_glm <- variable_attribution(explainer_glm, 
                               new_observation = x_test[1,],
                               type="break_down")

bd_glm2 <- variable_attribution(explainer_glm,
                                new_observation = x_test[30,],
                                type="break_down")
bd_colors <- c("#f05a71","#4378bf", "#8bdcbe", "#ffa58c")

p1 <- plot(bd_glm2, vcolors = bd_colors)
p2 <- plot(bd_glm, vcolors = bd_colors)
```

![image](https://user-images.githubusercontent.com/37885260/80012035-45280900-84ff-11ea-94be-4a2e65ae4c0c.png)

Thanks for your reply!

_Originally posted by @marcjermaine-pontiveros in https://github.com/ModelOriented/DALEX/issues/176#issuecomment-617911303_

**Comment by hbaniecki** [comment]
This issue was reported numerous times. A possible solution (implemented in `modelStudio`) is to place the `prediction` number on the left side of the `prediction` bar (so it is always visible).

**Comment by pbiecek** [comment]
@hbaniecki would you check if d574460 solves this issue? maybe I've missed something

**Comment by hbaniecki** [comment]
My intention was to place this text on the left side of the bar. The candidate fix is still better than no fix. Can we do the same for the intercept bar? See
```r
library("DALEX")
library("iBreakDown")
set.seed(1313)
model_titanic_glm <- glm(survived ~ gender + age + fare,
                         data = titanic_imputed, family = "binomial")
explain_titanic_glm <- explain(model_titanic_glm,
                               data = titanic_imputed,
                               y = titanic_imputed$survived,
                               label = "glm")

bd_glm <- local_attributions(explain_titanic_glm, titanic_imputed[1, ])
bd_glm
plot(bd_glm, max_features = 3, baseline=0.5)
```

**Comment by pbiecek** [comment]
thanks,
in a979cb4 the positioning works also for the intercept.

now it's on the right side, in next version we can add an option for this

**Comment by hbaniecki** [comment]
Thanks
