### ISSUE TITLE
More examples, and spellcheck

### ISSUE THREAD

**Issue by SimonDedman** [ModelOriented/iBreakDown#94]
Hi folks,

The package looks really interesting, but on github it says "Find lots of examples at the website: https://ModelOriented.github.io/iBreakDown/" but that only has the same example, plus the titanic walkthrough. It would be great to see some examples for different models.

Also, it might be good to run the pages & code through a spellcheck, e.g. I found loads of errors on https://modeloriented.github.io/iBreakDown/articles/vignette_iBreakDown_description.html , some of which look to be in the code itself.

Cheers!

**Comment by pbiecek** [comment]
I am sorry about that
Vignettes are often created by volunteers and it is not always feasible to check every description.
we have corrected some typos.
As far as documentation is concerned, currently the most complete description is https://ema.drwhy.ai/
