### ISSUE TITLE
How can we apply model oriented ibreakdown to complete data set

### ISSUE THREAD

**Issue by anuradham7** [ModelOriented/iBreakDown#95]
right now it just takes one observation at a time, is there any provision to run it for entire data set ?
bd_rf <- predict_parts(explainer = explain_rf,new_observation = test[1,] , type = "break_down")

**Comment by hbaniecki** [comment]
Hi, did you consider looping over the observations of interest? This is how I apply it in the [`modelStudio`](https://github.com/ModelOriented/modelStudio) package.

**Comment by pbiecek** [comment]
the reason was that the plot() function would not draw explanations well with predict_part() for multiple points.
With predict_profile(), you can draw all the profiles in one plot. But for predict_part() there is no good way to simultaneously draw multiple attributions for multiple observations.
